#pragma once
/*
  ==============================================================================

	 This file was auto-generated by the Jucer!

	 It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../../libs/juce/JuceLibraryCode/JuceHeader.h"
#include "../config/JucePluginCharacteristics.h"
#include "../plugin/SpectronAudioProcessor.h"
#include "SpectronAnalyzerComponent.h"
#include "../dsp/transformations/TransformationFactory.h"

//==============================================================================
/** This is the editor component that our filter will display.
*/
class SpectronMainUI  :	public AudioProcessorEditor
{
public:
	 static enum Constants {
		 MAINGUI_SIZE_X = 800,
		 MAINGUI_SIZE_Y = 360
	 };
	 SpectronMainUI (SpectronAudioProcessor* ownerFilter);
	 ~SpectronMainUI();

	 void paint (Graphics& g);
	 void resized();

private:
	 SpectronAnalyzerComponent	spectralAnalyzerComponent;
	 SpectronAudioProcessor*	getProcessor() const {return static_cast <SpectronAudioProcessor*> (getAudioProcessor());};
};

#endif  // __PLUGINEDITOR_H_4ACCBAA__
