#pragma once
/*
  ==============================================================================

	 This file was auto-generated by the Jucer!

	 It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../PluginProcessor.h"
#include "../dsp/transformations/TransformationFactory.h"
#include "juce_core/juce_core.h"
#include "SpectronAnalyzerComponent.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class SpectronMainUI : public juce::AudioProcessorEditor {
public:
    enum Constants {
        MAINGUI_SIZE_X = 800,
        MAINGUI_SIZE_Y = 360
    };
    explicit SpectronMainUI(SpectronAudioProcessor &ownerFilter);
    ~SpectronMainUI() override = default;

    void paint(juce::Graphics &graphics) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    SpectronAudioProcessor &audioProcessor;

    SpectronAnalyzerComponent spectralAnalyzerComponent;
};